spring:
  application:
    name: journalApp2

  data:
    mongodb:
      uri: "mongodb+srv://kaifalikhan347_db_user:3g0pYkttGDgRvvYf@cluster0.tq8fihk.mongodb.net/?appName=Cluster0"
      database: journaldb2
      auto-index-creation: true

server:
  port: 8080
