spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.journal.journalApp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
