spring.application.name=journalApp

spring.data.mongodb.uri=mongodb+srv://kaifalikhan347_db_user:3g0pYkttGDgRvvYf@cluster0.tq8fihk.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb2
spring.data.mongodb.auto-index-creation=true

logging.level.org.mongodb.driver=INFO
